# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:26
from __future__ import unicode_literals

import curiosoblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curiosoblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=curiosoblog.models.upload_location),
        ),
    ]
