# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:27
from __future__ import unicode_literals

import curiosoblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curiosoblog', '0002_auto_20170823_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=curiosoblog.models.upload_location, width_field='width_field'),
        ),
    ]
