# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curiosoblog', '0003_auto_20170823_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
