# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeforus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Profile', models.CharField(max_length=120)),
                ('Linkedin_Profile', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=120)),
            ],
        ),
    ]
