# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170824_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeforus',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='writeforus',
            name='Linkedin_Profile',
        ),
        migrations.RemoveField(
            model_name='writeforus',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='writeforus',
            name='content',
        ),
        migrations.RemoveField(
            model_name='writeforus',
            name='image',
        ),
        migrations.AddField(
            model_name='writeforus',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='writeforus',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
