# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170907_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeforus',
            name='attachment',
            field=models.ImageField(default=datetime.datetime(2017, 9, 7, 12, 22, 5, 855537, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
