# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170907_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='firstname',
            field=models.CharField(max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='career',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='writeforus',
            name='firstname',
            field=models.CharField(max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='writeforus',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='Last Name'),
        ),
    ]
